substitutions:
  device_description: Watermeter camera
  friendly_name: watermeter camera
  name: watermeter-camera

esphome:
  name: '${name}'
  friendly_name: '${friendly_name}'
  comment: '${device_description}'
  platformio_options:
    board_build.sdkconfig_opts: "CONFIG_LWIP_MAX_SOCKETS=32"
  on_boot:
    priority: 250
    then:
      - light.turn_on:
          id: meterRingLight
          brightness: 20%
          red: 100%
          green: 100%
          blue: 100%


esp32:
  board: esp32-s3-devkitc1-n16r8
  variant: ESP32S3
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

logger:
  level: DEBUG
  hardware_uart: UART0
  logs:
    esp32_camera: WARN
    mdns: WARN
    wifi: INFO

api:
  encryption:
    key: !secret home_assistant_key

ota:
  - platform: esphome

safe_mode:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80

esp32_camera_web_server:
  - port: 8080
    mode: snapshot
  - port: 8081
    mode: stream

i2c:
  - id: camera_i2c
    sda: GPIO4
    scl: GPIO5

esp32_camera:
  id: espcam
  name: esp-cam-2
  external_clock:
    pin: GPIO15
    frequency: 20MHz
  i2c_id: camera_i2c
  data_pins: [GPIO11, GPIO9, GPIO8, GPIO10, GPIO12, GPIO18, GPIO17, GPIO16]
  vsync_pin: GPIO6
  href_pin: GPIO7
  pixel_clock_pin: GPIO13
  resolution: 1600x1200
  jpeg_quality: 12
  max_framerate: 1.0fps
  idle_framerate: 0.2fps
  vertical_flip: true
  horizontal_mirror: false
  brightness: 0
  contrast: 0
  special_effect: none
  aec_mode: auto
  aec2: false
  ae_level: 0
  aec_value: 300
  agc_mode: auto
  agc_gain_ceiling: 2x
  agc_value: 0
  wb_mode: auto

light:
  - platform: esp32_rmt_led_strip
    pin: GPIO14
    num_leds: 24
    chipset: WS2812
    rgb_order: GRB
    id: meterRingLight
    name: ring light
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_ON
