services:
  meter_reader:
    build:
      context: .
      dockerfile: Dockerfile.reader
      target: production
    restart: unless-stopped
    user: "${DOCKER_UID}:${DOCKER_GID}"
    environment:
      CAM_SNAPSHOT_URL: ${CAM_SNAPSHOT_URL:-http://192.168.x.x/}
      READING_INTERVAL: ${READING_INTERVAL:-10}
      HA_URL:   ${HA_URL:-}
      HA_TOKEN: ${HA_TOKEN:-}
    volumes:
      - ./data:/app/data

  test:
    build:
      context: .
      dockerfile: Dockerfile.reader
      target: test
    volumes:
      - .:/app
    profiles: [test]
