services:
  collector:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      CAM_SNAPSHOT_URL: ${CAM_SNAPSHOT_URL:-http://192.168.x.x/}
      CAM_STREAM_URL:   ${CAM_STREAM_URL:-http://192.168.x.x:8080/}
      COLLECTOR_INTERVAL: ${COLLECTOR_INTERVAL:-10}
    volumes:
      - ./snapshots:/app/snapshots

  meter_reader:
    build:
      context: .
      dockerfile: Dockerfile.reader
      target: production
    restart: unless-stopped
    environment:
      CAM_SNAPSHOT_URL: ${CAM_SNAPSHOT_URL:-http://192.168.x.x/}
      READING_INTERVAL: ${READING_INTERVAL:-10}
      HA_URL:   ${HA_URL:-}
      HA_TOKEN: ${HA_TOKEN:-}
    volumes:
      - ./data:/app/data

  test:
    build:
      context: .
      dockerfile: Dockerfile.reader
      target: test
    profiles: [test]
